title: MikoInSpaceBlog
description: "Blog all about Space and Satellites"
logo_img: "/assets/miko.png"
profile_img: "/assets/img/miko.png"

# Social Links
email: mikoinspace@gmail.com
github_username: MikoInSpace
twitter_username: mikoinspace_
instagram_username: instagram

# External API
giscus_repo: "mikoinspaceblog/mikoinspaceblog.github.io"
giscus_repoId: "R_kgDOMLGL7Q"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOMLGL7c4Cgayn"
goatcounter_code: mikoinspace
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
